In [2]:
import pandas as pd
import requests
import numpy as np

In [9]:
df = pd.read_csv('StandardReportExports.csv', skiprows = 4, index_col = False, thousands=',')
df = df.drop(columns = ['Unnamed: 4'])

In [10]:
df1 = df[df.Time == '2014']
df1

,Time,Commodity,District,Value ($US)
0,2014,"3915 Waste, Parings And Scrap, Of Plastics",All Districts,953036078
1,2014,"3915 Waste, Parings And Scrap, Of Plastics","Anchorage, AK",369861
2,2014,"3915 Waste, Parings And Scrap, Of Plastics","Baltimore, MD",6301650
3,2014,"3915 Waste, Parings And Scrap, Of Plastics","Boston, MA",8014751
4,2014,"3915 Waste, Parings And Scrap, Of Plastics","Buffalo, NY",24017032
5,2014,"3915 Waste, Parings And Scrap, Of Plastics","Charleston, SC",52886821
6,2014,"3915 Waste, Parings And Scrap, Of Plastics","Chicago, IL",2120098
7,2014,"3915 Waste, Parings And Scrap, Of Plastics","Cleveland, OH",437932
8,2014,"3915 Waste, Parings And Scrap, Of Plastics","Columbia-Snake, OR",2414731
9,2014,"3915 Waste, Parings And Scrap, Of Plastics","Dallas-Fort Worth, TX",30197
10,2014,"3915 Waste, Parings And Scrap, Of Plastics","Detroit, MI",36253231
11,2014,"3915 Waste, Parings And Scrap, Of Plastics","Duluth, MN",2249688
12,2014,"3915 Waste, Parings And Scrap, Of Plastics","El Paso, TX",3273992
13,2014,"3915 Waste, Parings And Scrap, Of Plastics","Great Falls, MT",1919055
14,2014,"3915 Waste, Parings And Scrap, Of Plastics","Honolulu, HI",1843045
15,2014,"3915 Waste, Parings And Scrap, Of Plastics","Houston-Galveston, TX",49135688
16,2014,"3915 Waste, Parings And Scrap, Of Plastics","Laredo, TX",11807556
17,2014,"3915 Waste, Parings And Scrap, Of Plastics","Los Angeles, CA",365803307
18,2014,"3915 Waste, Parings And Scrap, Of Plastics",Low Value,3266808
19,2014,"3915 Waste, Parings And Scrap, Of Plastics","Miami, FL",16353023
20,2014,"3915 Waste, Parings And Scrap, Of Plastics","Minneapolis, MN",60368
21,2014,"3915 Waste, Parings And Scrap, Of Plastics","Mobile, AL",5665968
22,2014,"3915 Waste, Parings And Scrap, Of Plastics","New Orleans, LA",1303145
23,2014,"3915 Waste, Parings And Scrap, Of Plastics","New York City, NY",96726127
24,2014,"3915 Waste, Parings And Scrap, Of Plastics","Nogales, AZ",267692
25,2014,"3915 Waste, Parings And Scrap, Of Plastics","Norfolk, VA",46189036
26,2014,"3915 Waste, Parings And Scrap, Of Plastics","Ogdensburg, NY",14578109
27,2014,"3915 Waste, Parings And Scrap, Of Plastics","Pembina, ND",3791824
28,2014,"3915 Waste, Parings And Scrap, Of Plastics","Philadelphia, PA",660687
29,2014,"3915 Waste, Parings And Scrap, Of Plastics","Portland, ME",1103004
30,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Diego, CA",3224072
31,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Francisco, CA",74358111
32,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Juan, PR",4776084
33,2014,"3915 Waste, Parings And Scrap, Of Plastics","Savannah, GA",51972232
34,2014,"3915 Waste, Parings And Scrap, Of Plastics","Seattle, WA",39014615
35,2014,"3915 Waste, Parings And Scrap, Of Plastics","St. Albans, VT",3248972
36,2014,"3915 Waste, Parings And Scrap, Of Plastics","Tampa, FL",10765922
37,2014,"3915 Waste, Parings And Scrap, Of Plastics","Washington, DC",61848
38,2014,"3915 Waste, Parings And Scrap, Of Plastics","Wilmington, NC",6769796

In [11]:
df1['Value ($US)'].astype(int)

0     953036078
1        369861
2       6301650
3       8014751
4      24017032
5      52886821
6       2120098
7        437932
8       2414731
9         30197
10     36253231
11      2249688
12      3273992
13      1919055
14      1843045
15     49135688
16     11807556
17    365803307
18      3266808
19     16353023
20        60368
21      5665968
22      1303145
23     96726127
24       267692
25     46189036
26     14578109
27      3791824
28       660687
29      1103004
30      3224072
31     74358111
32      4776084
33     51972232
34     39014615
35      3248972
36     10765922
37        61848
38      6769796
Name: Value ($US), dtype: int64

In [13]:
df1.sort_values(by = 'Value ($US)')

,Time,Commodity,District,Value ($US)
9,2014,"3915 Waste, Parings And Scrap, Of Plastics","Dallas-Fort Worth, TX",30197
20,2014,"3915 Waste, Parings And Scrap, Of Plastics","Minneapolis, MN",60368
37,2014,"3915 Waste, Parings And Scrap, Of Plastics","Washington, DC",61848
24,2014,"3915 Waste, Parings And Scrap, Of Plastics","Nogales, AZ",267692
1,2014,"3915 Waste, Parings And Scrap, Of Plastics","Anchorage, AK",369861
7,2014,"3915 Waste, Parings And Scrap, Of Plastics","Cleveland, OH",437932
28,2014,"3915 Waste, Parings And Scrap, Of Plastics","Philadelphia, PA",660687
29,2014,"3915 Waste, Parings And Scrap, Of Plastics","Portland, ME",1103004
22,2014,"3915 Waste, Parings And Scrap, Of Plastics","New Orleans, LA",1303145
14,2014,"3915 Waste, Parings And Scrap, Of Plastics","Honolulu, HI",1843045
13,2014,"3915 Waste, Parings And Scrap, Of Plastics","Great Falls, MT",1919055
6,2014,"3915 Waste, Parings And Scrap, Of Plastics","Chicago, IL",2120098
11,2014,"3915 Waste, Parings And Scrap, Of Plastics","Duluth, MN",2249688
8,2014,"3915 Waste, Parings And Scrap, Of Plastics","Columbia-Snake, OR",2414731
30,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Diego, CA",3224072
35,2014,"3915 Waste, Parings And Scrap, Of Plastics","St. Albans, VT",3248972
18,2014,"3915 Waste, Parings And Scrap, Of Plastics",Low Value,3266808
12,2014,"3915 Waste, Parings And Scrap, Of Plastics","El Paso, TX",3273992
27,2014,"3915 Waste, Parings And Scrap, Of Plastics","Pembina, ND",3791824
32,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Juan, PR",4776084
21,2014,"3915 Waste, Parings And Scrap, Of Plastics","Mobile, AL",5665968
2,2014,"3915 Waste, Parings And Scrap, Of Plastics","Baltimore, MD",6301650
38,2014,"3915 Waste, Parings And Scrap, Of Plastics","Wilmington, NC",6769796
3,2014,"3915 Waste, Parings And Scrap, Of Plastics","Boston, MA",8014751
36,2014,"3915 Waste, Parings And Scrap, Of Plastics","Tampa, FL",10765922
16,2014,"3915 Waste, Parings And Scrap, Of Plastics","Laredo, TX",11807556
26,2014,"3915 Waste, Parings And Scrap, Of Plastics","Ogdensburg, NY",14578109
19,2014,"3915 Waste, Parings And Scrap, Of Plastics","Miami, FL",16353023
4,2014,"3915 Waste, Parings And Scrap, Of Plastics","Buffalo, NY",24017032
10,2014,"3915 Waste, Parings And Scrap, Of Plastics","Detroit, MI",36253231
34,2014,"3915 Waste, Parings And Scrap, Of Plastics","Seattle, WA",39014615
25,2014,"3915 Waste, Parings And Scrap, Of Plastics","Norfolk, VA",46189036
15,2014,"3915 Waste, Parings And Scrap, Of Plastics","Houston-Galveston, TX",49135688
33,2014,"3915 Waste, Parings And Scrap, Of Plastics","Savannah, GA",51972232
5,2014,"3915 Waste, Parings And Scrap, Of Plastics","Charleston, SC",52886821
31,2014,"3915 Waste, Parings And Scrap, Of Plastics","San Francisco, CA",74358111
23,2014,"3915 Waste, Parings And Scrap, Of Plastics","New York City, NY",96726127
17,2014,"3915 Waste, Parings And Scrap, Of Plastics","Los Angeles, CA",365803307
0,2014,"3915 Waste, Parings And Scrap, Of Plastics",All Districts,953036078